"""
Prompts package - System prompts for LLM
"""

from .system_prompts import (
    EXTRACT_SYSTEM_PROMPT_STRUCTURED,
    DIFF_ANALYSIS_PROMPT_STRUCTURED,
    REPLY_SYSTEM_PROMPT,
    DEPENDENCY_WARNING_PROMPT,
    QUIZ_SYSTEM_PROMPT_STRUCTURED,
    DIGEST_SYSTEM_PROMPT,
    PATTERN_ANALYSIS_SYSTEM_PROMPT,
)

__all__ = [
    'EXTRACT_SYSTEM_PROMPT_STRUCTURED',
    'DIFF_ANALYSIS_PROMPT_STRUCTURED',
    'REPLY_SYSTEM_PROMPT',
    'DEPENDENCY_WARNING_PROMPT',
    'QUIZ_SYSTEM_PROMPT_STRUCTURED',
    'DIGEST_SYSTEM_PROMPT',
    'PATTERN_ANALYSIS_SYSTEM_PROMPT',
]
